### ISSUE TITLE
error in make

### ISSUE THREAD

**Issue by usatpath01** [JeongyoonMoon/lsmbpf_demo#1]
I am trying to execute the code. but it is giving the following error:
/usr/bin/ld: cannot find -lcap: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:54: /lsm-bpf/usr/prog_lsm] Error 1
@JeongyoonMoon Can you please help with it, what is causing the issue?

**Comment by JeongyoonMoon** [comment]
Hi, I guess `libcap-dev` is missing in your environment. 
Can you retry after installing it with `sudo apt install libcap-dev`? 
Plus, make sure you install all the required packages to run this program.
